# Generated by Django 4.2.2 on 2023-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='maxchoices',
            field=models.IntegerField(default=1),
        ),
    ]
