# Generated by Django 4.2.2 on 2023-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_election_contact_email_election_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
