# Generated by Django 4.2.2 on 2023-06-15 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_first_name', models.CharField(blank=True, max_length=100)),
                ('default_last_name', models.CharField(blank=True, max_length=100)),
                ('default_url', models.URLField(blank=True, null=True)),
                ('sciper', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('where', models.CharField(blank=True, max_length=200, null=True)),
                ('units', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('memberof', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
