name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Python ${{ matrix.python }} / Django ${{ matrix.django }} CI

    strategy:
      fail-fast: false
      matrix:
        python: ['3.8.7']
        django: ['4.2.2']

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade tox tox-gh-actions

      - name: Tox tests
        run: |
          tox -v

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          name: Python ${{ matrix.python }} / Django ${{ matrix.django }}
